module.exports = {
    "MHA": 'PT. Central Sole Agency (Volvo)',
    "93V": 'Audi Brazil',
    "1V1": 'Volkswagen USA (commercials)',
    "WV3": 'Volkswagen Trucks',
    "WVG": 'Volkswagen SUVs (Gelande)',
    "935": "Citroën Brazil",
    "936": "Peugeot Brazil",
    "4TL": "Toyota",
    "JMG": "Mazda",
    "3GE": "General Motors Mexico",
    "5TP": "Toyota USA - trucks",
    "5F5": "Honda USA-Alabama",
    "5LH": "Lincoln",
    "1GP": "General Motors USA",
    "KL9": "Daewoo General Motors South Korea",
    "6AB": "MAN Australia",
    "JMV": "Mazda",
    "JM5": "Mazda",
    "JFL": "Fuji Heavy Industries",
    "5FX": "Honda USA-Alabama",
    "1HK": "Honda USA",
    "JAL": "Isuzu",
    "MA1": "Mahindra",
    "1NT": "Nissan USA",
    "2M7": "Mercury",
    "JSC": "Suzuki",
    "VF6": "Renault (Trucks & Buses)",
    "JM1": "Mazda",
    "1N2": "Nissan USA",
    "2TK": "Toyota Canada",
    "1LZ": "Lincoln USA",
    "2MC": "Mercury",
    "JMM": "Mazda",
    "2GZ": "General Motors Canada",
    "JMT": "Mazda",
    "3NM": "Nissan Mexico",
    "ZFC": "Fiat V.I.",
    "4ML": "Mercury",
    "5FL": "Honda USA-Alabama",
    "1NM": "Nissan USA",
    "WV2": "Volkswagen Bus/Van",
    "5FM": "Honda USA-Alabama",
    "JSV": "Suzuki",
    "JM6": "Mazda",
    "5L9": "Lincoln",
    "1N6": "Nissan USA",
    "3P3": "Plymouth Mexico",
    "JAT": "Isuzu",
    "1GX": "General Motors USA",
    "JNZ": "Nissan",
    "TMT": "Tatra (Czech Republic)",
    "2GD": "General Motors Canada",
    "4T5": "Toyota",
    "1FA": "Ford Motor Company",
    "JHM": "Honda",
    "4TZ": "Toyota",
    "JNJ": "Nissan",
    "KPA": "Ssangyong",
    "1H7": "Honda USA",
    "JT0": "Toyota",
    "1GV": "General Motors USA",
    "4SM": "Subaru-Isuzu Automotive",
    "JAH": "Isuzu",
    "4FA": "Mazda USA",
    "JTE": "Toyota",
    "4TU": "Toyota",
    "2G6": "General Motors Canada",
    "4MF": "Mercury",
    "1FC": "Ford Motor Company",
    "4ST": "Subaru-Isuzu Automotive",
    "JAA": "Isuzu",
    "1H4": "Honda USA",
    "4S7": "Subaru-Isuzu Automotive",
    "JTD": "Toyota",
    "JMB": "Mazda",
    "4SR": "Subaru-Isuzu Automotive",
    "2GK": "General Motors Canada",
    "5FB": "Honda USA-Alabama",
    "5LV": "Lincoln",
    "2M1": "Mercury",
    "4SB": "Subaru-Isuzu Automotive",
    "4MK": "Mercury",
    "2TR": "Toyota Canada",
    "LVS": "Ford Chang An",
    "JN3": "Nissan",
    "1L8": "Lincoln USA",
    "4TH": "Toyota",
    "3GK": "General Motors Mexico",
    "JKY": "Kawasaki",
    "1HR": "Honda USA",
    "3GR": "General Motors Mexico",
    "JAW": "Isuzu",
    "4US": "BMW USA",
    "1HT": "Honda USA",
    "4TX": "Toyota",
    "3G4": "General Motors Mexico",
    "4F7": "Mazda USA",
    "2G1": "Chevrolet Canada",
    "JS2": "Suzuki",
    "3G9": "General Motors Mexico",
    "3NL": "Nissan Mexico",
    "JSR": "Suzuki",
    "1LL": "Lincoln USA",
    "JA7": "Isuzu",
    "1HJ": "Honda USA",
    "KLE": "Daewoo General Motors South Korea",
    "JKU": "Kawasaki",
    "4SK": "Subaru-Isuzu Automotive",
    "JF6": "Fuji Heavy Industries",
    "3HH": "Honda Mexico",
    "8AJ": "Toyota Argentina",
    "LZG": "Shaanxi Automobile Group",
    "2GC": "General Motors Canada",
    "5TN": "Toyota USA - trucks",
    "JS3": "Suzuki",
    "WDB": "Mercedes-Benz",
    "3N0": "Nissan Mexico",
    "W0L": "Opel",
    "MMM": "Chevrolet Thailand",
    "5LT": "Lincoln",
    "1G1": "Chevrolet USA",
    "4SC": "Subaru-Isuzu Automotive",
    "JKT": "Kawasaki",
    "L56": "Renault Samsung",
    "4T3": "Toyota",
    "2MT": "Mercury",
    "LZY": "Yutong Zhengzhou",
    "JKR": "Kawasaki",
    "VF1": "Renault",
    "SCE": "DeLorean Motor Cars N. Ireland (UK)",
    "JM3": "Mazda",
    "4T4": "Toyota",
    "JSH": "Suzuki",
    "4FU": "Mazda USA",
    "5T4": "Toyota USA - trucks",
    "5L8": "Lincoln",
    "2TL": "Toyota Canada",
    "JKL": "Kawasaki",
    "4F2": "Mazda USA",
    "JSN": "Suzuki",
    "JF9": "Fuji Heavy Industries",
    "3HW": "Honda Mexico",
    "1NF": "Nissan USA",
    "3FE": "Ford Motor Company Mexico",
    "UU1": "Renault Dacia",
    "1M2": "Mack Truck USA",
    "1NV": "Nissan USA",
    "6H8": "General Motors-Holden (pre Nov 2002)",
    "3HG": "Honda Mexico",
    "JND": "Nissan",
    "3GT": "General Motors Mexico",
    "3H3": "Honda Mexico",
    "JAX": "Isuzu",
    "JNA": "Nissan",
    "KL3": "Daewoo General Motors South Korea",
    "VNE": "Irisbus (France)",
    "1N5": "Nissan USA",
    "3GC": "General Motors Mexico",
    "WF0": "Ford Germany",
    "3HN": "Honda Mexico",
    "4SA": "Subaru-Isuzu Automotive",
    "JN8": "Nissan",
    "4V4": "Volvo",
    "2GW": "General Motors Canada",
    "4FC": "Mazda USA",
    "AAV": "Volkswagen South Africa",
    "JT3": "Toyota",
    "JAS": "Isuzu",
    "4FY": "Mazda USA",
    "4TE": "Toyota",
    "JN2": "Nissan",
    "3N1": "Nissan Mexico",
    "1ME": "Mercury USA",
    "3HV": "Honda Mexico",
    "KNA": "Kia",
    "9BF": "Ford Motor Company Brazil",
    "2TD": "Toyota Canada",
    "JK6": "Kawasaki",
    "4SS": "Subaru-Isuzu Automotive",
    "JAB": "Isuzu",
    "JNT": "Nissan",
    "YS3": "Saab",
    "KLL": "Daewoo General Motors South Korea",
    "2WL": "Western Star",
    "1HG": "Honda USA",
    "3GH": "General Motors Mexico",
    "8AG": "Chevrolet Argentina",
    "2MF": "Mercury",
    "1YV": "Mazda USA (AutoAlliance International)",
    "2TW": "Toyota Canada",
    "JNY": "Nissan",
    "1LM": "Lincoln USA",
    "5TY": "Toyota USA - trucks",
    "JSM": "Suzuki",
    "3NU": "Nissan Mexico",
    "5TC": "Toyota USA - trucks",
    "5T1": "Toyota USA - trucks",
    "4S1": "Subaru-Isuzu Automotive",
    "1LS": "Lincoln USA",
    "2FA": "Ford Motor Company Canada",
    "JM4": "Mazda",
    "5TD": "Toyota USA - trucks",
    "5FV": "Honda USA-Alabama",
    "JAP": "Isuzu",
    "JTY": "Toyota",
    "3GY": "General Motors Mexico",
    "5LD": "Lincoln",
    "2TJ": "Toyota Canada",
    "8AD": "Peugeot Argentina",
    "4SZ": "Subaru-Isuzu Automotive",
    "JF1": "Fuji Heavy Industries",
    "JNB": "Nissan",
    "2GP": "General Motors Canada",
    "JSB": "Suzuki",
    "JTB": "Toyota",
    "TDM": "QUANTYA Swiss Electric Movement (Switzerland)",
    "4MP": "Mercury",
    "JAD": "Isuzu",
    "4T8": "Toyota",
    "JN5": "Nissan",
    "5T9": "Toyota USA - trucks",
    "1GJ": "General Motors USA",
    "3GU": "General Motors Mexico",
    "JKC": "Kawasaki",
    "JK1": "Kawasaki",
    "4FB": "Mazda USA",
    "JAU": "Isuzu",
    "6G1": "General Motors-Holden (post Nov 2002)",
    "JMD": "Mazda",
    "3GX": "General Motors Mexico",
    "VF3": "Peugeot",
    "ZAM": "Maserati Biturbo",
    "2GL": "General Motors Canada",
    "1D3": "Dodge",
    "1XP": "Peterbilt USA",
    "3HX": "Honda Mexico",
    "3GF": "General Motors Mexico",
    "TRU": "Audi Hungary",
    "5LS": "Lincoln",
    "2MM": "Mercury",
    "JST": "Suzuki",
    "2MA": "Mercury",
    "TSM": "Suzuki",
    "1H1": "Honda USA",
    "2GN": "General Motors Canada",
    "3GL": "General Motors Mexico",
    "1HW": "Honda USA",
    "4F4": "Mazda USA",
    "2GH": "General Motors Canada",
    "3G3": "General Motors Mexico",
    "4M6": "Mercury",
    "1N3": "Nissan USA",
    "JA8": "Isuzu",
    "JAE": "Isuzu",
    "NM4": "Tofas Turk",
    "JFG": "Fuji Heavy Industries",
    "KNC": "Kia",
    "3NG": "Nissan Mexico",
    "1HA": "Honda USA",
    "1GW": "General Motors USA",
    "JM9": "Mazda",
    "3HE": "Honda Mexico",
    "1NK": "Nissan USA",
    "1L2": "Lincoln USA",
    "2M3": "Mercury",
    "5L5": "Lincoln",
    "JTA": "Toyota",
    "4M8": "Mercury",
    "2C3": "Chrysler Canada",
    "XL9": "Spyker",
    "JAR": "Isuzu",
    "2TT": "Toyota Canada",
    "1NA": "Nissan USA",
    "4SN": "Subaru-Isuzu Automotive",
    "3D3": "Dodge Mexico",
    "2MN": "Mercury",
    "4M4": "Mercury",
    "4TB": "Toyota",
    "4M1": "Mercury",
    "JFF": "Fuji Heavy Industries",
    "2T5": "Toyota Canada",
    "YS2": "Scania AB",
    "5T5": "Toyota USA - trucks",
    "PE3": "Mazda Phillipines",
    "2WK": "Western Star",
    "5TR": "Toyota USA - trucks",
    "JS0": "Suzuki",
    "JS1": "Suzuki",
    "JS8": "Suzuki",
    "5LW": "Lincoln",
    "JNC": "Nissan",
    "4F3": "Mazda USA",
    "1P3": "Plymouth USA",
    "4MJ": "Mercury",
    "3FA": "Ford Motor Company Mexico",
    "1ND": "Nissan USA",
    "3N4": "Nissan Mexico",
    "3N3": "Nissan Mexico",
    "4FK": "Mazda USA",
    "1R9": "Roadrunner Hay Squeeze USA",
    "2FZ": "Sterling",
    "5LX": "Lincoln",
    "1GM": "Pontiac USA",
    "1GB": "General Motors USA",
    "5FW": "Honda USA-Alabama",
    "2MR": "Mercury",
    "4FL": "Mazda USA",
    "1H0": "Honda USA",
    "4SH": "Subaru-Isuzu Automotive",
    "3GJ": "General Motors Mexico",
    "1HE": "Honda USA",
    "1LA": "Lincoln USA",
    "2GB": "General Motors Canada",
    "4FE": "Mazda USA",
    "4V1": "Volvo",
    "JKP": "Kawasaki",
    "1L9": "Lincoln USA",
    "ZCG": "Cagiva SpA",
    "2G3": "Oldsmobile Canada",
    "1N1": "Nissan USA",
    "JMX": "Mazda",
    "1G3": "Oldsmobile USA",
    "1L5": "Lincoln USA",
    "JN0": "Nissan",
    "93H": "Honda Brazil",
    "2T0": "Toyota Canada",
    "2G4": "Buick Canada",
    "KLW": "Daewoo General Motors South Korea",
    "5TV": "Toyota USA - trucks",
    "2MW": "Mercury",
    "KLC": "Daewoo General Motors South Korea",
    "4FP": "Mazda USA",
    "2T4": "Toyota Canada",
    "TMP": "Škoda trolleybuses (Czech Republic)",
    "JS4": "Suzuki",
    "JK9": "Kawasaki",
    "JAJ": "Isuzu",
    "4TG": "Toyota",
    "3HY": "Honda Mexico",
    "4T0": "Toyota",
    "JN7": "Nissan",
    "JSK": "Suzuki",
    "JN6": "Nissan",
    "TK9": "SOR (Czech Republic)",
    "WEB": "Evobus GmbH (Mercedes-Bus)",
    "3NY": "Nissan Mexico",
    "NM0": "Ford Turkey",
    "4TY": "Toyota",
    "3NK": "Nissan Mexico",
    "2MY": "Mercury",
    "5LJ": "Lincoln",
    "MPA": "Isuzu Thailand",
    "JTL": "Toyota",
    "4TW": "Toyota",
    "4M0": "Mercury",
    "4SW": "Subaru-Isuzu Automotive",
    "3HS": "Honda Mexico",
    "2TN": "Toyota Canada",
    "4M2": "Mercury",
    "4FZ": "Mazda USA",
    "MRH": "Honda Thailand",
    "1LF": "Lincoln USA",
    "2M4": "Mercury",
    "2GE": "General Motors Canada",
    "JNU": "Nissan",
    "1GS": "General Motors USA",
    "ZAR": "Alfa Romeo",
    "KL1": "Daewoo General Motors South Korea",
    "JNE": "Nissan",
    "2M2": "Mercury",
    "VSS": "SEAT",
    "JKV": "Kawasaki",
    "WAU": "Audi",
    "4TT": "Toyota",
    "8AK": "Suzuki Argentina",
    "1F9": "FWD Corp.",
    "3H6": "Honda Mexico",
    "4S0": "Subaru-Isuzu Automotive",
    "4MV": "Mercury",
    "JNS": "Nissan",
    "KLX": "Daewoo General Motors South Korea",
    "1NZ": "Nissan USA",
    "5TG": "Toyota USA - trucks",
    "JMH": "Mazda",
    "5TF": "Toyota USA - trucks",
    "5TZ": "Toyota USA - trucks",
    "SDB": "Peugeot UK",
    "4SG": "Subaru-Isuzu Automotive",
    "JSY": "Suzuki",
    "JA2": "Isuzu",
    "KLK": "Daewoo General Motors South Korea",
    "5F2": "Honda USA-Alabama",
    "VLU": "Scania France",
    "1LG": "Lincoln USA",
    "KLZ": "Daewoo General Motors South Korea",
    "JAF": "Isuzu",
    "1GZ": "General Motors USA",
    "4SX": "Subaru-Isuzu Automotive",
    "5TS": "Toyota USA - trucks",
    "JK7": "Kawasaki",
    "JMC": "Mazda",
    "5TH": "Toyota USA - trucks",
    "MR0": "Toyota Thailand",
    "5FE": "Honda USA-Alabama",
    "KLP": "Daewoo General Motors South Korea",
    "2T8": "Toyota Canada",
    "KLV": "Daewoo General Motors South Korea",
    "4SV": "Subaru-Isuzu Automotive",
    "1HU": "Honda USA",
    "93R": "Toyota Brazil",
    "5LL": "Lincoln",
    "5TB": "Toyota USA - trucks",
    "ZHW": "Lamborghini",
    "3GD": "General Motors Mexico",
    "JAK": "Isuzu",
    "JK5": "Kawasaki",
    "ZDM": "Ducati Motor Holdings SpA",
    "1LY": "Lincoln USA",
    "3N9": "Nissan Mexico",
    "4FM": "Mazda USA",
    "4MS": "Mercury",
    "4F8": "Mazda USA",
    "3GA": "General Motors Mexico",
    "JNW": "Nissan",
    "2MJ": "Mercury",
    "JTR": "Toyota",
    "JSX": "Suzuki",
    "KL0": "Daewoo General Motors South Korea",
    "JFK": "Fuji Heavy Industries",
    "1LP": "Lincoln USA",
    "2TM": "Toyota Canada",
    "3NR": "Nissan Mexico",
    "JT6": "Toyota",
    "8AF": "Ford Motor Company Argentina",
    "1HS": "Honda USA",
    "5LA": "Lincoln",
    "3G0": "General Motors Mexico",
    "5L6": "Lincoln",
    "3GZ": "General Motors Mexico",
    "5FJ": "Honda USA-Alabama",
    "1GF": "General Motors USA",
    "2MV": "Mercury",
    "4MX": "Mercury",
    "5FH": "Honda USA-Alabama",
    "JFV": "Fuji Heavy Industries",
    "TM9": "Škoda trolleybuses (Czech Republic)",
    "2TZ": "Toyota Canada",
    "4UZ": "Frt-Thomas Bus",
    "JSF": "Suzuki",
    "5T8": "Toyota USA - trucks",
    "1LB": "Lincoln USA",
    "KLS": "Daewoo General Motors South Korea",
    "JHL": "Honda",
    "JTH": "Toyota",
    "4FX": "Mazda USA",
    "1GU": "General Motors USA",
    "4T7": "Toyota",
    "1H9": "Honda USA",
    "3HL": "Honda Mexico",
    "2TU": "Toyota Canada",
    "JSG": "Suzuki",
    "JN4": "Nissan",
    "VV9": "TAUROSpain",
    "1LH": "Lincoln USA",
    "1GH": "General Motors USA",
    "KLM": "Daewoo General Motors South Korea",
    "5LF": "Lincoln",
    "1G4": "Buick USA",
    "2M6": "Mercury",
    "2TG": "Toyota Canada",
    "5FZ": "Honda USA-Alabama",
    "SCA": "Rolls Royce",
    "3NA": "Nissan Mexico",
    "JFC": "Fuji Heavy Industries",
    "4M5": "Mercury",
    "VF8": "Matra",
    "2FV": "Freightliner",
    "VF7": "Citroën",
    "3NS": "Nissan Mexico",
    "JNG": "Nissan",
    "2HK": "Honda Canada",
    "5TU": "Toyota USA - trucks",
    "1GT": "GMC Truck USA",
    "SAL": "Land Rover",
    "2FT": "Ford Motor Company Canada",
    "2MZ": "Mercury",
    "2M5": "Mercury",
    "JNM": "Nissan",
    "3GS": "General Motors Mexico",
    "3NF": "Nissan Mexico",
    "JSS": "Suzuki",
    "JKZ": "Kawasaki",
    "JKH": "Kawasaki",
    "3H2": "Honda Mexico",
    "JKG": "Kawasaki",
    "1VW": "Volkswagen USA",
    "6FP": "Ford Motor Company Australia",
    "JA9": "Isuzu",
    "ZAP": "Piaggio/Vespa/Gilera",
    "MA7": "Honda Siel Cars India",
    "4MZ": "Mercury",
    "SHS": "Honda UK",
    "8GG": "Chevrolet Chile",
    "4FG": "Mazda USA",
    "1NW": "Nissan USA",
    "1GA": "General Motors USA",
    "4F6": "Mazda USA",
    "JM7": "Mazda",
    "4FJ": "Mazda USA",
    "WV1": "Volkswagen Commercial Vehicles",
    "2ME": "Mercury",
    "4TN": "Toyota",
    "1L1": "Lincoln USA",
    "3G7": "General Motors Mexico",
    "JF4": "Fuji Heavy Industries",
    "1GY": "General Motors USA",
    "5FA": "Honda USA-Alabama",
    "1H2": "Honda USA",
    "VSX": "Opel Spain",
    "TMB": "Škoda (Czech Republic)",
    "6F5": "Kenworth Australia",
    "JSU": "Suzuki",
    "2MX": "Mercury",
    "JMF": "Mazda",
    "5FN": "Honda USA-Alabama",
    "1NP": "Nissan USA",
    "1NB": "Nissan USA",
    "2GF": "General Motors Canada",
    "LSY": "Brilliance Zhonghua",
    "4RK": "Nova Bus USA",
    "4V2": "Volvo",
    "ZFA": "Fiat",
    "3NB": "Nissan Mexico",
    "JS5": "Suzuki",
    "JT4": "Toyota",
    "1LR": "Lincoln USA",
    "1GK": "General Motors USA",
    "4VL": "Volvo",
    "JK0": "Kawasaki",
    "JSA": "Suzuki",
    "3HA": "Honda Mexico",
    "JFE": "Fuji Heavy Industries",
    "4F0": "Mazda USA",
    "4SU": "Subaru-Isuzu Automotive",
    "1GD": "General Motors USA",
    "JTV": "Toyota",
    "YV4": "Volvo Cars",
    "JAM": "Isuzu",
    "1L6": "Lincoln USA",
    "JKD": "Kawasaki",
    "1FB": "Ford Motor Company",
    "3HU": "Honda Mexico",
    "3NV": "Nissan Mexico",
    "JFH": "Fuji Heavy Industries",
    "KLT": "Daewoo General Motors South Korea",
    "4SL": "Subaru-Isuzu Automotive",
    "3ND": "Nissan Mexico",
    "1HM": "Honda USA",
    "5FD": "Honda USA-Alabama",
    "4MD": "Mercury",
    "4MT": "Mercury",
    "JTM": "Toyota",
    "JF7": "Fuji Heavy Industries",
    "5F3": "Honda USA-Alabama",
    "2WM": "Western Star",
    "1LC": "Lincoln USA",
    "4SJ": "Subaru-Isuzu Automotive",
    "XMC": "Mitsubishi (NedCar)",
    "JFN": "Fuji Heavy Industries",
    "JA0": "Isuzu",
    "KL6": "Daewoo General Motors South Korea",
    "KNB": "Kia",
    "JTJ": "Toyota",
    "JKS": "Kawasaki",
    "2G2": "Pontiac Canada",
    "KNM": "Renault Samsung",
    "2MB": "Mercury",
    "5LP": "Lincoln",
    "JSD": "Suzuki",
    "KL5": "Daewoo General Motors South Korea",
    "JSJ": "Suzuki",
    "5T7": "Toyota USA - trucks",
    "JTF": "Toyota",
    "6G2": "Pontiac Australia (GTO & G8)",
    "1M9": "Mynatt Truck & Equipment",
    "MAL": "Hyundai",
    "9BM": "Mercedes-Benz Brazil",
    "JT9": "Toyota",
    "KL7": "Daewoo General Motors South Korea",
    "WBS": "BMW M",
    "JTN": "Toyota",
    "ZLA": "Lancia",
    "2GS": "General Motors Canada",
    "1N8": "Nissan USA",
    "1G9": "General Motors USA",
    "JTS": "Toyota",
    "5FT": "Honda USA-Alabama",
    "MM8": "Mazda Thailand",
    "3HB": "Honda Mexico",
    "1LV": "Lincoln USA",
    "1N9": "Nissan USA",
    "YS4": "Scania Bus",
    "JNL": "Nissan",
    "1LJ": "Lincoln USA",
    "1HX": "Honda USA",
    "4MR": "Mercury",
    "4TR": "Toyota",
    "3NC": "Nissan Mexico",
    "JTX": "Toyota",
    "2FM": "Ford Motor Company Canada",
    "3GM": "General Motors Mexico",
    "JFT": "Fuji Heavy Industries",
    "SAJ": "Jaguar",
    "3N2": "Nissan Mexico",
    "KLR": "Daewoo General Motors South Korea",
    "4MC": "Mercury",
    "1G7": "General Motors USA",
    "1N4": "Nissan USA",
    "1HL": "Honda USA",
    "JT5": "Toyota",
    "2HG": "Honda Canada",
    "JNN": "Nissan",
    "2P3": "Plymouth Canada",
    "4SY": "Subaru-Isuzu Automotive",
    "5TT": "Toyota USA - trucks",
    "1NL": "Nissan USA",
    "1HD": "Harley-Davidson",
    "JFZ": "Fuji Heavy Industries",
    "JNF": "Nissan",
    "1FV": "Freightliner",
    "VS6": "Ford Spain",
    "JAZ": "Isuzu",
    "LKL": "Suzhou King Long",
    "JKF": "Kawasaki",
    "JKE": "Kawasaki",
    "2G8": "General Motors Canada",
    "5TW": "Toyota USA - trucks",
    "4MU": "Mercury",
    "2GV": "General Motors Canada",
    "1HN": "Honda USA",
    "JS7": "Suzuki",
    "5FK": "Honda USA-Alabama",
    "5F1": "Honda USA-Alabama",
    "JS9": "Suzuki",
    "ZDF": "Ferrari Dino",
    "JNV": "Nissan",
    "4T1": "Toyota",
    "TN9": "Karosa (Czech Republic)",
    "SCC": "Lotus Cars",
    "1L3": "Lincoln USA",
    "3HF": "Honda Mexico",
    "1HZ": "Honda USA",
    "2T2": "Toyota Canada",
    "1HP": "Honda USA",
    "1C6": "Chrysler",
    "KLU": "Daewoo General Motors South Korea",
    "5NP": "Hyundai USA",
    "PE1": "Ford Phillipines",
    "2TA": "Toyota Canada",
    "3G6": "General Motors Mexico",
    "4TP": "Toyota",
    "5L0": "Lincoln",
    "3HK": "Honda Mexico",
    "3HT": "Honda Mexico",
    "4FN": "Mazda USA",
    "1N7": "Nissan USA",
    "JAC": "Isuzu",
    "3GP": "General Motors Mexico",
    "JT8": "Toyota",
    "4TJ": "Toyota",
    "2T7": "Toyota Canada",
    "KL8": "Daewoo General Motors South Korea",
    "JTZ": "Toyota",
    "4T6": "Toyota",
    "2ML": "Mercury",
    "5N1": "Nissan USA",
    "JF0": "Fuji Heavy Industries",
    "1L0": "Lincoln USA",
    "4M9": "Mercury",
    "3H9": "Honda Mexico",
    "JTT": "Toyota",
    "4FW": "Mazda USA",
    "NMT": "Toyota Turkiye",
    "JFJ": "Fuji Heavy Industries",
    "4F1": "Mazda USA",
    "5TA": "Toyota USA - trucks",
    "JKX": "Kawasaki",
    "4FV": "Mazda USA",
    "YV3": "Volvo Buses",
    "5FG": "Honda USA-Alabama",
    "JKN": "Kawasaki",
    "5F4": "Honda USA-Alabama",
    "4S6": "Subaru-Isuzu Automotive",
    "MNT": "Nissan Thailand",
    "1HY": "Honda USA",
    "JT1": "Toyota",
    "3N8": "Nissan Mexico",
    "2T3": "Toyota Canada",
    "YV1": "Volvo Cars",
    "1LN": "Lincoln USA",
    "JFX": "Fuji Heavy Industries",
    "JSZ": "Suzuki",
    "1LE": "Lincoln USA",
    "5FF": "Honda USA-Alabama",
    "1GL": "General Motors USA",
    "JK2": "Kawasaki",
    "4S4": "Subaru-Isuzu Automotive",
    "SCF": "Aston",
    "9BS": "Scania Brazil",
    "8A1": "Renault Argentina",
    "5LM": "Lincoln",
    "2TE": "Toyota Canada",
    "JTG": "Toyota",
    "1GC": "Chevrolet Truck USA",
    "YV2": "Volvo Trucks",
    "JK8": "Kawasaki",
    "1LU": "Lincoln USA",
    "JK3": "Kawasaki",
    "5TX": "Toyota USA - trucks",
    "3G8": "General Motors Mexico",
    "JS6": "Suzuki",
    "JA6": "Isuzu",
    "3GV": "General Motors Mexico",
    "5LE": "Lincoln",
    "1GR": "General Motors USA",
    "1N0": "Nissan USA",
    "1H6": "Honda USA",
    "4S9": "Subaru-Isuzu Automotive",
    "5L7": "Lincoln",
    "5T0": "Toyota USA - trucks",
    "8GD": "Peugeot Chile",
    "1NX": "NUMMI USA",
    "4T2": "Toyota",
    "2CN": "CAMI",
    "4ME": "Mercury",
    "LZM": "MAN China",
    "5L3": "Lincoln",
    "2FB": "Ford Motor Company Canada",
    "1GN": "General Motors USA",
    "3HJ": "Honda Mexico",
    "2TV": "Toyota Canada",
    "KLF": "Daewoo General Motors South Korea",
    "1G0": "General Motors USA",
    "2MS": "Mercury",
    "4MG": "Mercury",
    "2D3": "Dodge Canada",
    "3H1": "Honda Mexico",
    "JSE": "Suzuki",
    "5TE": "Toyota USA - trucks",
    "1LD": "Lincoln USA",
    "MA3": "Suzuki India",
    "JA5": "Isuzu",
    "5LY": "Lincoln",
    "93U": "Audi Brazil",
    "4S2": "Subaru-Isuzu Automotive",
    "4FD": "Mazda USA",
    "4S8": "Subaru-Isuzu Automotive",
    "JFU": "Fuji Heavy Industries",
    "2GR": "General Motors Canada",
    "YK1": "Saab",
    "4SP": "Subaru-Isuzu Automotive",
    "2GJ": "General Motors Canada",
    "3N5": "Nissan Mexico",
    "TRA": "Ikarus Bus",
    "SJN": "Nissan UK",
    "5FS": "Honda USA-Alabama",
    "JSL": "Suzuki",
    "KMH": "Hyundai",
    "2M8": "Mercury",
    "JFD": "Fuji Heavy Industries",
    "JML": "Mazda",
    "2TB": "Toyota Canada",
    "4M7": "Mercury",
    "9BG": "Chevrolet Brazil",
    "1NY": "Nissan USA",
    "JAY": "Isuzu",
    "1HH": "Honda USA",
    "5LK": "Lincoln",
    "JMN": "Mazda",
    "3H4": "Honda Mexico",
    "5L4": "Lincoln",
    "3NH": "Nissan Mexico",
    "1J4": "Jeep",
    "5LN": "Lincoln",
    "AFA": "Ford South Africa",
    "JTC": "Toyota",
    "2GT": "General Motors Canada",
    "9FB": "Renault Colombia",
    "3H5": "Honda Mexico",
    "5LG": "Lincoln",
    "MP1": "Isuzu Thailand",
    "1FT": "Ford Motor Company",
    "JKK": "Kawasaki",
    "TMK": "Karosa (Czech Republic)",
    "1NN": "Nissan USA",
    "2TY": "Toyota Canada",
    "4SE": "Subaru-Isuzu Automotive",
    "5LB": "Lincoln",
    "3HC": "Honda Mexico",
    "3H7": "Honda Mexico",
    "5TM": "Toyota USA - trucks",
    "1C3": "Chrysler",
    "4S3": "Subaru-Isuzu Automotive",
    "2V4": "Volkswagen Canada",
    "6MM": "Mitsubishi Motors Australia",
    "1NC": "Nissan USA",
    "WMA": "MAN Germany",
    "4TA": "Toyota",
    "5F9": "Honda USA-Alabama",
    "5TJ": "Toyota USA - trucks",
    "5FP": "Honda USA-Alabama",
    "JNH": "Nissan",
    "4SF": "Subaru-Isuzu Automotive",
    "4FS": "Mazda USA",
    "5F7": "Honda USA-Alabama",
    "SAR": "Rover",
    "SFD": "Alexander Dennis UK",
    "VSK": "Nissan Spain",
    "VX1": "Zastava / Yugo Serbia",
    "1HF": "Honda USA",
    "1LT": "Lincoln USA",
    "1H3": "Honda USA",
    "4VZ": "Volvo",
    "JNK": "Nissan",
    "JM0": "Mazda",
    "3NX": "Nissan Mexico",
    "2M9": "Mercury",
    "2MK": "Mercury",
    "2MD": "Mercury",
    "6F4": "Nissan Motor Company Australia",
    "1M1": "Mack Truck USA",
    "2MU": "Mercury",
    "5LU": "Lincoln",
    "8AW": "Volkswagen Argentina",
    "KLB": "Daewoo General Motors South Korea",
    "4V3": "Volvo",
    "2TX": "Toyota Canada",
    "JF3": "Fuji Heavy Industries",
    "4VM": "Volvo",
    "2MP": "Mercury",
    "JFP": "Fuji Heavy Industries",
    "3GB": "General Motors Mexico",
    "5L1": "Lincoln",
    "2M0": "Mercury",
    "MNB": "Ford Thailand",
    "JAN": "Isuzu",
    "MMB": "Mitsubishi Thailand",
    "2GA": "General Motors Canada",
    "PL1": "Proton",
    "4MM": "Mercury",
    "SU9": "Solaris Bus & Coach (Poland)",
    "5T6": "Toyota USA - trucks",
    "2MG": "Mercury",
    "JKA": "Kawasaki",
    "L5Y": "Merato Motorcycle Taizhou Zhongneng",
    "3HP": "Honda Mexico",
    "2GM": "General Motors Canada",
    "4SD": "Subaru-Isuzu Automotive",
    "JFS": "Fuji Heavy Industries",
    "KLY": "Daewoo General Motors South Korea",
    "4MB": "Mercury",
    "1GE": "General Motors USA",
    "JNP": "Nissan",
    "KLJ": "Daewoo General Motors South Korea",
    "JMR": "Mazda",
    "JHG": "Honda",
    "4MW": "Mercury",
    "5FR": "Honda USA-Alabama",
    "JKW": "Kawasaki",
    "1H5": "Honda USA",
    "5T3": "Toyota USA - trucks",
    "MC2": "Volvo Eicher commercial vehicles limited.",
    "KLG": "Daewoo General Motors South Korea",
    "4FF": "Mazda USA",
    "LGH": "Dong Feng (DFM)",
    "JA1": "Isuzu",
    "JTK": "Toyota",
    "4MA": "Mercury",
    "4S5": "Subaru-Isuzu Automotive",
    "JMY": "Mazda",
    "5FY": "Honda USA-Alabama",
    "2G9": "General Motors Canada",
    "3G1": "General Motors Mexico",
    "KL2": "Daewoo General Motors South Korea",
    "5F0": "Honda USA-Alabama",
    "3HR": "Honda Mexico",
    "LVV": "Chery",
    "KPT": "Ssangyong",
    "1L4": "Lincoln USA",
    "5FC": "Honda USA-Alabama",
    "KLN": "Daewoo General Motors South Korea",
    "5F6": "Honda USA-Alabama",
    "1NR": "Nissan USA",
    "5L2": "Lincoln",
    "5T2": "Toyota USA - trucks",
    "1FU": "Freightliner",
    "WAG": "Neoplan",
    "4FH": "Mazda USA",
    "JFA": "Fuji Heavy Industries",
    "1H8": "Honda USA",
    "3G5": "General Motors Mexico",
    "TSE": "Ikarus Egyedi Autobuszgyar",
    "2HM": "Hyundai Canada",
    "2T9": "Toyota Canada",
    "4TC": "Toyota",
    "4MY": "Mercury",
    "9BW": "Volkswagen Brazil",
    "1NU": "Nissan USA",
    "2NV": "Nova Bus Canada",
    "5LC": "Lincoln",
    "3VW": "Volkswagen Mexico",
    "6U9": "Privately Imported car in Australia",
    "ZD4": "Aprilia",
    "LDY": "Zhongtong Coach",
    "KLD": "Daewoo General Motors South Korea",
    "JT2": "Toyota",
    "JTW": "Toyota",
    "JAG": "Isuzu",
    "KL4": "Daewoo General Motors South Korea",
    "JA4": "Isuzu",
    "4FR": "Mazda USA",
    "4T9": "Toyota",
    "4V6": "Volvo",
    "LZE": "Isuzu Guangzhou",
    "3NP": "Nissan Mexico",
    "JMA": "Mazda",
    "2G0": "General Motors Canada",
    "8AP": "Fiat Argentina",
    "1G8": "Saturn USA",
    "VSE": "Suzuki Spain (Santana Motors)",
    "JMZ": "Mazda",
    "4V5": "Volvo",
    "5LZ": "Lincoln",
    "JFR": "Fuji Heavy Industries",
    "JM2": "Mazda",
    "5TL": "Toyota USA - trucks",
    "JN9": "Nissan",
    "2G5": "General Motors Canada",
    "3H0": "Honda Mexico",
    "93Y": "Renault Brazil",
    "JF8": "Fuji Heavy Industries",
    "JKJ": "Kawasaki",
    "JSP": "Suzuki",
    "2TF": "Toyota Canada",
    "WDC": "DaimlerChrysler",
    "WDD": "McLaren",
    "3HM": "Honda Mexico",
    "WMW": "MINI",
    "3NW": "Nissan Mexico",
    "2T6": "Toyota Canada",
    "MHR": "Honda Indonesia",
    "1L7": "Lincoln USA",
    "3N7": "Nissan Mexico",
    "JFM": "Fuji Heavy Industries",
    "JMJ": "Mazda",
    "JM8": "Mazda",
    "2TP": "Toyota Canada",
    "1GG": "General Motors USA",
    "JFY": "Fuji Heavy Industries",
    "JFB": "Fuji Heavy Industries",
    "3NE": "Nissan Mexico",
    "6T1": "Toyota Motor Corporation Australia",
    "NLE": "Mercedes-Benz Turk Truck",
    "1NG": "Nissan USA",
    "1NE": "Nissan USA",
    "5TK": "Toyota USA - trucks",
    "2TS": "Toyota Canada",
    "4F9": "Mazda USA",
    "4MN": "Mercury",
    "WVW": "Volkswagen",
    "JTP": "Toyota",
    "4MH": "Mercury",
    "KM8": "Hyundai",
    "JTU": "Toyota",
    "4TF": "Toyota",
    "JMS": "Mazda",
    "3NN": "Nissan Mexico",
    "2TC": "Toyota Canada",
    "4TV": "Toyota",
    "2T1": "Toyota Canada",
    "2GX": "General Motors Canada",
    "JK4": "Kawasaki",
    "JMU": "Mazda",
    "JF5": "Fuji Heavy Industries",
    "WP0": "Porsche",
    "JNX": "Nissan",
    "1G5": "General Motors USA",
    "JNR": "Nissan",
    "JF2": "Fuji Heavy Industries",
    "JKB": "Kawasaki",
    "JME": "Mazda",
    "JA3": "Isuzu",
    "1G2": "Pontiac USA",
    "VWV": "Volkswagen Spain",
    "2GU": "General Motors Canada",
    "4TK": "Toyota",
    "1HV": "Honda USA",
    "VS9": "Carrocerias Ayats (Spain)",
    "1FD": "Ford Motor Company",
    "JMP": "Mazda",
    "KLH": "Daewoo General Motors South Korea",
    "4TD": "Toyota",
    "2MH": "Mercury",
    "2FC": "Ford Motor Company Canada",
    "1G6": "Cadillac USA",
    "9BD": "Fiat Brazil",
    "3HZ": "Honda Mexico",
    "JAV": "Isuzu",
    "2G7": "General Motors Canada",
    "WBA": "BMW",
    "JT7": "Toyota",
    "JKM": "Kawasaki",
    "3N6": "Nissan Mexico",
    "1LX": "Lincoln USA",
    "JMK": "Mazda",
    "3NT": "Nissan Mexico",
    "5F8": "Honda USA-Alabama",
    "KLA": "Daewoo General Motors South Korea",
    "2GG": "General Motors Canada",
    "3GW": "General Motors Mexico",
    "4F5": "Mazda USA",
    "1M3": "Mack Truck USA",
    "1LW": "Lincoln USA",
    "4M3": "Mercury",
    "3GN": "General Motors Mexico",
    "1NS": "Nissan USA",
    "1NH": "Nissan USA",
    "1XK": "Kenworth USA",
    "2TH": "Toyota Canada",
    "1HC": "Honda USA",
    "1NJ": "Nissan USA",
    "JFW": "Fuji Heavy Industries",
    "JSW": "Suzuki",
    "ZFF": "Ferrari",
    "LTV": "Toyota Tian Jin",
    "3G2": "General Motors Mexico",
    "4FT": "Mazda USA",
    "3H8": "Honda Mexico",
    "3GG": "General Motors Mexico",
    "3HD": "Honda Mexico",
    "4TS": "Toyota",
    "2FU": "Freightliner",
    "1FM": "Ford Motor Company",
    "1LK": "Lincoln USA",
    "JMW": "Mazda",
    "2GY": "General Motors Canada",
    "4TM": "Toyota",
    "5LR": "Lincoln",
    "ZOM": "OM",
    "3NJ": "Nissan Mexico",
    "MMT": "Mitsubishi Thailand",
    "1M4": "Mack Truck USA",
    "1HB": "Honda USA",
    "3NZ": "Nissan Mexico",
    "JN1": "Nissan",
    "5FU": "Honda USA-Alabama",

    // xUSSR manufacturer
    // list source: https://uk.wikipedia.org/wiki/Ідентифікаційний_номер_транспортного_засобу

    // Russia
    "XSE": 'IMZ-Ural Ltd. "Russian motorcycles", Russia',
    "XTA": 'Lada/AutoVaz, Togliatti, Russia',
    "XTB": 'JSC "Moskvich" - the Moscow Automobile Plant, Russia',
    "XTC": 'Open Joint Stock Company "KAMAZ" (Kama Automobile Plant), Russia',
    "XTF": 'JSC "Golitsyn Bus Plant" (HolAZ), Russia',
    "XTH": 'GAS, "Gorky Automobile Plant", Russia',
    "XTJ": 'JSC "Serpukhov Automobile Plant" ( "SeAZ"), Russia',
    "XTK": 'Izhevsk Automobile Plant ("IzhAvto"), Russia',
    "XTP": 'JSC "Metrovagonmash" (until 1992 - "Mytyschenskyy engineering plant" or MMP), Russia',
    "XTT": 'JSC "UAZ", Russia',
    "XTU": 'JSC "trolza" (fully Closed Joint Stock Company "trolza"), Russia',
    "XTY": 'LiAZ, Russia',
    "XTZ": 'Car Plant. IA Likhachev, Russia',
    "XUS": 'Nyzhehorodets, Russia',
    "XVD": 'SemAR, Russia',
    "XVG": 'Company "Michurinsk bus" (Michurinsk avtoremontnыy plant Marz), Russia',
    "XWF": 'Avtotor - a company producing cars in Kaliningrad, Russia',
    "XWK": 'Izhevsk Automobile Plant ("IzhAvto"), Russia',
    "XWN": 'Armor Group, Russia',
    "X06": 'DYSA Auto, Russia',
    "X08": 'Myhnevskyy RMZ, Russia',
    "X0C": 'TagAZ, Taganrog, Russia',
    "X0J": 'Company "Mercator Servis ST", Russia',
    "X0P": 'Company "Perspective-K", Kazan, Russia',
    "X0T": 'MZ "TONAR" Orekhovo-Zuevo, Russia',
    "X0Y": 'Rodnikovskoe Machine Works, Russia',
    "X1A": 'HZSA, Nizhny Novgorod, Russia',
    "X1F": 'NEFAZ, Neftekamsk, Russia',
    "X1J": 'KZAP, Krasnoyarsk, Russia',
    "X1L": 'TMZ, Tavda, Russia',
    "X1M": 'PAZ, Pavlovo, Russia',
    "X1P": 'UralAZ, Miass, Russia',
    "X1E": 'KAvZ, Kurgan, Russia',

    // Ukraine
    "XSG": 'Odessa car assembly plant ODAZ, Ukraine',
    "XSL": 'Lvov factory motorcycles, Ukraine',
    "XSP": 'Kyiv Motorcycle Plant, Ukraine',
    "XSW": 'JOINT "5 Kiev car repair PLANT", Ukraine',
    "XTD": 'Lutsk Automobile Plant, JSC, Ukraine',
    "XTE": 'PJSC Zaporizhia Automobile Plant (JSC "ZAZ"), Ukraine',
    "XTG": 'Ltd. "Kherson car assembly plant" Anto-Rus "(Antorus), Ukraine',
    "XTV": 'Lugansk Car Assembly Plant, Ukraine',
    "XTW": 'Lviv Bus Plant (LAZ), Ukraine',
    "XTX": 'Odessa car assembly plant ODAZ, Ukraine',
    "X1C": 'Kremenchug Automobile Plant, Ukraine',

    // Belarus
    "XTM": 'Minsk Automobile Plant (MAZ), Minsk, Belarus',
    "X1R": 'BelAZ, Zhodino, Belarus',

    // Uzbekistan
    "XWB": 'UZ-Daewoo Auto, Asaka, Uzbekistan',

    // Kazakhstan
    "XWW": 'Asia-Auto, Ust-Kamenogorsk, Kazakhstan',

    // Latvia
    "X1D":'RAF, Riga, Latvia',

    // Unsorted (Need to translate from Ukrainian)
    "X1S": 'Zid, Kovrov, Russia',
    "X1V": 'Kuban, Krasnodar, Russia',
    "X1W": 'SZAP, Stavropol, Russia',
    "X1X": 'Kupava, Minsk, Belarus',
    "X3W": '"Betsema", Krasnogorsk, Russia',
    "X3Z": 'Resurrection plant "Mashynostroytel", Voskresensk, Russia',
    "X4K": 'VAP "Volzhanin", Volzhsky, Russia',
    "X52": 'Company "Transles", Khimki, Russia',
    "X5C": 'LLC "Trailer", Stupino, Russia',
    "X5F": 'OJSC "Hydraulic lifter vehicles», St. Petersburg, Russia',
    "X5T": 'OJSC "41 central plant zheleznodorozhnoy technics", Tomilino, Russia',
    "X6F": 'Company "Spector Motors", v. Bratovschyna (Moscow region), Russia',
    "X7D": 'RosLada, Syzran, Russia',
    "X7M": 'TagAZ, Taganrog (Rostov region), Russia',
    "X7T": 'CHAZ, Chernihiv, Ukraine',
    "X8U": 'Scania-Peter, Saint-Petersburg, Russia',
    "X9L": 'GM-AVTOVAZ, Togliatti (Samara Region), Russia',
    "X9N": 'Company "Samotlor-NN", Nizhny Novgorod, Russia',
    "X9U": 'LLC "Almanac", Nizhny Novgorod, Russia',
    "X9X": 'LLC "Autotrade-12", s. Novoharytonovo (Moscow region), Russia',
    "Y3B": 'BelAZ, Zhodino, Belarus',
    "Y3C": 'MoAZ, Mogilev, Belarus',
    "Y3J": 'BKM, Minsk, Belarus',
    "Y3M": 'MAZ, Minsk, Belarus',
    "Y4F": 'Ford Union Minsk, Abchak (Belarus)',
    "Y6A": 'AutoKrAZ, Ukraine, Kremenchug',
    "Y6D": 'ZAZ, Zaporozhe, Ukraine',
    "Y6J": 'Repair plant Cherkasy, Cherkasy, Ukraine',
    "Y6L": 'LuAZ, Lutsk, Ukraine',
    "Y6R": 'Kherson car assembly factory «Anto-Rus", Kherson, Ukraine',
    "Y6V": 'FDI Kitpred, Kyiv, Ukraine',
    "Y69": 'Bohdan SpecAutomotive, Cherkasy, Ukraine /  Budmash, Kyiv, Ukraine / TITAL, Kyiv, Ukraine',
    "Y7A": 'AutoKrAZ, Ukraine, Kremenchug',
    "Y7B": 'Cherkasy Bus, Ukraine, Cherkasy ',
    "Y7C": 'Kremenchuk Car Assembly Plant, Kremenchuk, Ukraine',
    "Y7F": 'BAZ, Boryspil, Ukraine',
    "Y7K": 'CMH, Kyiv, Ukraine',
    "Y79": 'HalAZ, Lviv, Ukraine',
    "Y8A": 'Lviv Bus Plant (LAZ), Ukraine',
    "Y89": 'Yuzhmash,Dnipropetrovsk, Ukraine',
    "Z7C": '"Louis", Nizhny Novgorod, Russia',
    "Z7G": 'LLC "Sollers-Yelabuga», Yelabuga, Russia',
    "Z7T": 'RoAZ, Rostov-on-Don, Russia',
    "Z7Y": '"Artan", Nizhny Novgorod, Russia',
    "Z9Z": 'OOO "United Auto Group", Izhevsk, Russia',
    "X89": 'Little xUSSR factories',
    "Y39": 'Little xUSSR factories'

};
